spring:
    application:
        name: springcloudlearing

    datasource:
#        type: com.mysql.cj.jdbc.MysqlDataSource
        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.253.129:33306/insound?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: root
        druid:
            max-active: 1024
            initial-size: 5
            min-idle: 5
            max-wait: 60000
#            filter:
#                wall:
#                    enable: true
#                    db-type: mysql
#                stat:
#                    enable: true
#                    db-type: mysql
        url: jdbc:p6spy:mysql://192.168.253.129:33306/insound?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver


decorator:
    datasource:
        p6spy:
            #日志格式
            log-format: time:%(executionTime) || sql:%(sql)
            #自定义日志类
            logging: custom
            custom-appender-class: com.baomidou.mybatisplus.extension.p6spy.StdoutLogger


management:
    #开启信息可显示
    info:
        env:
            enabled: true
    endpoints:
        web:
            exposure:
                include: "*"

    endpoint:
        health:
            show-details: always
info:
    name: "zhulw"
    sex: "femal"
    birth: "22"
    info:
        app:
            encoding: "@project.build.sourceEncoding@"
            java:
                source: "@java.version@"
                target: "@java.version@"
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
